version : '3.3'
services :
  isolate :
    image : hotcode002/isolate:local
    ports : 
      - "8080:8080"
    volumes : 
      - C:/Users/siva/Documents/poc/code-sandbox:/root/code-sandbox
    privileged : true
    # sysctls :
      # systemd.unified_cgroup_hierarchy : false
      # systemd.legacy_systemd_cgroup_controller: false
    command :
      - /bin/bash
      - -c
      - |
        cd /root/code-sandbox
        git checkout dev
        npm install
        npm run dev