version : '1'
services :
  isolate :
    image : siva002/isolate:latest
    ports : 
      - "80:8080"
    privileged : true
    command :
      - /bin/bash
      - -c
      - |
        cd /root/code-sandbox
        npm run dev