version : '1'
services :
  isolate :
    image : siva002/isolate:latest
    ports : 
      - "8080:8080"
    privileged : true
    # sysctls :
      # systemd.unified_cgroup_hierarchy : false
      # systemd.legacy_systemd_cgroup_controller: false
    command :
      - /bin/bash
      - -c
      - |
        cd /root/code-sandbox-master
        npm install
        npm run dev