version : '3.3'
services :
  isolate :
    image : hotcode002/isolate:dev
    ports : 
      - "80:8080"
    privileged : true
    command :
      - /bin/bash
      - -c
      - |
        cd /root/code-sandbox
        git checkout dev
        npm start