POST {{url}}/submissions/xx
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "C",
    "source_code" : "#include <stdio.h> \n int main() \n { \n printf(\"Hello, World!\"); \n return 0; \n }"
}

###
POST {{url}}/submissions
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "C",
    "source_code" : "#include <stdio.h> \n int main() \n { \n printf(\"Hello, World!\"); \n return 0; \n }"
}


###

POST {{url}}/submissions
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "JAVA",
    "source_code" : "class Main { \n public static void main(String[] args) { \n System.out.println(\"Hello, Java World!\");  \n } \n }"
}

###

POST {{url}}/submissions
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "CPP",
    "source_code" : "#include <iostream> \n int main() \n { \n     std::cout << \"Hello World C++!\"; \n return 0; \n }"
}

###

POST {{url}}/submissions
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "PYTHON",
    "source_code" : "print(\"Hello World Python\")"
}

###
POST {{url}}/submissions
Authorization: Bearer {{$dotenv %token}}
Content-Type: application/json

{
    "id" : "xxx",
    "callback_url" : "http://localhost:8080/",
    "language" : "JAVASCRIPT",
    "source_code" : "console.log(\"Hello World Javascript\")"
}

###
